kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph-fast
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.146.0.7:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: k8s
  userId: k8s
  userSecretName: ceph-secret-user
  userSecretNamespace: default
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
